### ISSUE TITLE
TileMill on Yosemitie

### ISSUE THREAD

**Issue by markledsome** [joeyklee/joeyklee.github.io#1]
Hi Joey,

If you select update preferences and check 'install developer builds' you will get a functioning version of Tile Mill for OSX 10.10.   That worked for me this afternoon.  Hopefully it's a bit simpler solution for your participants than clone and build from source.

Perhaps by the time you do your seminar the 'stable build' will be updated and working, and this will be a non-issue.

**Comment by joeyklee** [comment]
Hi Mark,

Oh wow! This is super good news. I’ll check this out and update my readme.

Thanks so much!

Best,
Joey
